version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - 27017:27017

  springdockercompose:
    image: springdockercompose:latest
    container_name: "springdockercompose"
    ports:
      - 9090:8080
    links:
      - mongo_db
